version: '2.0'
services:
  alerta-web:
    image: www.owlemon.com/alerta-web:2017.02.08
    container_name: alerta-web
    ports:
      - 8181:80
    depends_on:
      - alerta-db
    environment:
      - MONGO_URI=mongodb://alerta-db:27017/monitoring
    volumes:
      - $PWD/config/alertad.conf.example:/etc/alertad.conf
      - $PWD/config/config.js.example:/app/config.js
    restart: always
  alerta-db:
    image: www.owlemon.com/mongo:2017.02.08
    container_name: mongo
    volumes:
      - ./mongodb:/data/db
    restart: always
